### ISSUE TITLE
Tests fail on master

### ISSUE THREAD

**Issue by gldraphael** [AlexPoint/SubtitlesParser#16]
The tests seem to fail with the following output:

```
Parsing of file 20140120-074450_invalidSub: FAILURE
System.FormatException: Failed to parse as SubtitlesParser.Classes.SubtitlesFormat ---> System.ArgumentException: Stream is not in a valid Srt format
   at SubtitlesParser.Classes.Parsers.SrtParser.ParseStream(Stream srtStream, Encoding encoding) in C:\Users\galdin\source\repos\SubtitlesParser\SubtitlesParser\Classes\Parsers\SrtParser.cs:line 104
   at SubtitlesParser.Classes.Parsers.SubParser.ParseStream(Stream stream, Encoding encoding, Dictionary`2 subFormatDictionary) in C:\Users\galdin\source\repos\SubtitlesParser\SubtitlesParser\Classes\Parsers\SubParser.cs:line 120
   --- End of inner exception stack trace ---
   at SubtitlesParser.Classes.Parsers.SubParser.ParseStream(Stream stream, Encoding encoding, Dictionary`2 subFormatDictionary) in C:\Users\galdin\source\repos\SubtitlesParser\SubtitlesParser\Classes\Parsers\SubParser.cs:line 125
   at SubtitlesParser.Classes.Parsers.SubParser.ParseStream(Stream stream, Encoding encoding, SubtitlesFormat subFormat) in C:\Users\galdin\source\repos\SubtitlesParser\SubtitlesParser\Classes\Parsers\SubParser.cs:line 85
   at Test.Program.Main(String[] args) in C:\Users\galdin\source\repos\SubtitlesParser\Test\Program.cs:line 26
----------------------
Parsing of file 4989_ES.srt: SUCCESS (1092 items - 0% corrupted)
----------------
----------------------
Parsing of file ccSubs_com_pope-francis-speaks-about-religious-liberty_en.srt: SUCCESS (25 items - 8% corrupted)
----------------
----------------------
Parsing of file Children.of.Men.2006.DVD5.720p.HDDVD.x264-REVEiLLE.srt: SUCCESS (985 items - 0% corrupted)
----------------
----------------------
Parsing of file cloudy.with.a.risk.of.meatballs.ttml: SUCCESS (1109 items - 0% corrupted)
----------------
----------------------
Parsing of file Example With Comments.vtt: SUCCESS (2 items - 0% corrupted)
----------------
----------------------
Parsing of file Fight Club_eng.sub: FAILURE
System.FormatException: Failed to parse as SubtitlesParser.Classes.SubtitlesFormat ---> System.ArgumentException: Stream is not in a valid MicroDVD format
   at SubtitlesParser.Classes.Parsers.MicroDvdParser.ParseStream(Stream subStream, Encoding encoding) in C:\Users\galdin\source\repos\SubtitlesParser\SubtitlesParser\Classes\Parsers\MicroDvdParser.cs:line 111
   at SubtitlesParser.Classes.Parsers.SubParser.ParseStream(Stream stream, Encoding encoding, Dictionary`2 subFormatDictionary) in C:\Users\galdin\source\repos\SubtitlesParser\SubtitlesParser\Classes\Parsers\SubParser.cs:line 120
   --- End of inner exception stack trace ---
   at SubtitlesParser.Classes.Parsers.SubParser.ParseStream(Stream stream, Encoding encoding, Dictionary`2 subFormatDictionary) in C:\Users\galdin\source\repos\SubtitlesParser\SubtitlesParser\Classes\Parsers\SubParser.cs:line 125
   at SubtitlesParser.Classes.Parsers.SubParser.ParseStream(Stream stream, Encoding encoding, SubtitlesFormat subFormat) in C:\Users\galdin\source\repos\SubtitlesParser\SubtitlesParser\Classes\Parsers\SubParser.cs:line 85
   at Test.Program.Main(String[] args) in C:\Users\galdin\source\repos\SubtitlesParser\Test\Program.cs:line 26
----------------------
Parsing of file Game of Thrones - 03x05 - Kissed by Fire.2HD.English.HI.C.orig.Addic7ed.com.srt: FAILURE
System.FormatException: Failed to parse as SubtitlesParser.Classes.SubtitlesFormat ---> System.ArgumentException: Stream is not in a valid Srt format
   at SubtitlesParser.Classes.Parsers.SrtParser.ParseStream(Stream srtStream, Encoding encoding) in C:\Users\galdin\source\repos\SubtitlesParser\SubtitlesParser\Classes\Parsers\SrtParser.cs:line 104
   at SubtitlesParser.Classes.Parsers.SubParser.ParseStream(Stream stream, Encoding encoding, Dictionary`2 subFormatDictionary) in C:\Users\galdin\source\repos\SubtitlesParser\SubtitlesParser\Classes\Parsers\SubParser.cs:line 120
   --- End of inner exception stack trace ---
   at SubtitlesParser.Classes.Parsers.SubParser.ParseStream(Stream stream, Encoding encoding, Dictionary`2 subFormatDictionary) in C:\Users\galdin\source\repos\SubtitlesParser\SubtitlesParser\Classes\Parsers\SubParser.cs:line 125
   at SubtitlesParser.Classes.Parsers.SubParser.ParseStream(Stream stream, Encoding encoding, SubtitlesFormat subFormat) in C:\Users\galdin\source\repos\SubtitlesParser\SubtitlesParser\Classes\Parsers\SubParser.cs:line 85
   at Test.Program.Main(String[] args) in C:\Users\galdin\source\repos\SubtitlesParser\Test\Program.cs:line 26
----------------------
Parsing of file Gangs-of-New-York-DVD-Deadman-2.sub: SUCCESS (748 items - 0% corrupted)
----------------
----------------------
Parsing of file kYB8IZa5AuE.en.ttml: SUCCESS (169 items - 0% corrupted)
----------------
----------------------
Parsing of file No Captions - With comment block.vtt: SUCCESS (No items found!)
----------------------
Parsing of file Orange.is.the.new.black.s01e01.ttml: SUCCESS (813 items - 0% corrupted)
----------------
----------------------
Parsing of file Salvage.SRT: SUCCESS (474 items - 0% corrupted)
----------------
----------------------
Parsing of file The Mentalist - 3x11 - Episode 11.fr.srt: SUCCESS (786 items - 0% corrupted)
----------------
----------------------
Parsing of file timedtext.xml: FAILURE
System.FormatException: Failed to parse as SubtitlesParser.Classes.SubtitlesFormat ---> System.ArgumentException: Stream is not in a valid Srt format
   at SubtitlesParser.Classes.Parsers.SrtParser.ParseStream(Stream srtStream, Encoding encoding) in C:\Users\galdin\source\repos\SubtitlesParser\SubtitlesParser\Classes\Parsers\SrtParser.cs:line 104
   at SubtitlesParser.Classes.Parsers.SubParser.ParseStream(Stream stream, Encoding encoding, Dictionary`2 subFormatDictionary) in C:\Users\galdin\source\repos\SubtitlesParser\SubtitlesParser\Classes\Parsers\SubParser.cs:line 120
   --- End of inner exception stack trace ---
   at SubtitlesParser.Classes.Parsers.SubParser.ParseStream(Stream stream, Encoding encoding, Dictionary`2 subFormatDictionary) in C:\Users\galdin\source\repos\SubtitlesParser\SubtitlesParser\Classes\Parsers\SubParser.cs:line 125
   at SubtitlesParser.Classes.Parsers.SubParser.ParseStream(Stream stream, Encoding encoding, SubtitlesFormat subFormat) in C:\Users\galdin\source\repos\SubtitlesParser\SubtitlesParser\Classes\Parsers\SubParser.cs:line 85
   at Test.Program.Main(String[] args) in C:\Users\galdin\source\repos\SubtitlesParser\Test\Program.cs:line 26
----------------------
Parsing of file Wiedzmin.s01e01.DVDRip.DreamLair.srt: SUCCESS (233 items - 0% corrupted)
----------------
----------------------
```

**Comment by AlexPoint** [comment]
Thanks for your feedback.
The test are badly written - I was quite inexperienced at writing tests at the time - but no, they do not fail. The parsing failures that we observe are normal because either the files are invalid or their format.
It's not that clear though and will update the tests to make them clearer once I have some time.

**Comment by gldraphael** [comment]
Oh, no in that case let it be. I'll send a PR to use xunit tests instead.
